### ISSUE TITLE
Package citation

### ISSUE THREAD

**Issue by feddelegrand7** [the-y-company/many#5]
Im glad that you got your inspiration from my package that does exactly the same thing and which I have developed months ago but you should give a little bit credit to this package. 

https://cran.r-project.org/web/packages/rfold/index.html

**Comment by feddelegrand7** [comment]
Ah @JohnCoene you're the developer? I didn't know at the beginning

**Comment by JohnCoene** [comment]
Apologies, I did not know about rfold and did not take inspiration from it. Do you see similarities in the code/API/execution that makes you say I took inspiration from it?

**Comment by feddelegrand7** [comment]
@JohnCoene no worries. I know your work and how serious and ethic you are. To answer your question. I don't have to look into the code base. The main idea is exactly the same. The goal and the method to achieve that are the same. That's why I supposed that you took inspiration from my package.

**Comment by JohnCoene** [comment]
I added a mention of {rfold} in the README.

I had not seen your package, and {many} is in no inspired from it. I'm happy to mention it as related work but I honestly wished you asked differently.

I think you should take a look at the code, the implementation is rather different.

**Comment by JohnCoene** [comment]
Right, I thought it could be "all good," I tried to make it "all good" by adding a link to rfold in the README of this package.

It seems really strange that you can claim your package needs to be cited when you say yourself you have not looked at the code.
Again, it works very differently and you would only know if you tried it or looked at the code but you refuse to do that.

Also, even if there is an existing package that allows doing something similar does not mean others are not entitled to their own implementation. Perhaps after this you can head over to {data.table} and tell them to cite {dplyr} since it objectively do the same thing.

I owe nothing to rfold or you, I did not have to add a mention of rfold in the README but I did thinking it may just calm things down but you had to come back with another cynical comment. So I simply have to retract the olive branch I extended and remove rfold from the README since it does not satisfy anyway. I will then delete this issue.

I do not spend my free time producing work for the community to be treated like this.
